### ISSUE TITLE
Change symbol for user activation in "users" section

### ISSUE THREAD

**Issue by lewikg** [enricoba/turtle-lab#86]
Intuitively looks like a delete command

**Comment by enricoba** [comment]
what kind of icon do you have in mind? check the icon set available https://fontawesome.com/icons?d=gallery&q=user

**Comment by lewikg** [comment]
Thanks for the link. Intuitively, I'd go with the "user plus" icon

**Comment by enricoba** [comment]
sounds good, so lets go for "user check" :).
